/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PProjectIdRouteRouteImport } from './routes/p/$projectId/route'
import { Route as PProjectIdShellRouteRouteImport } from './routes/p/$projectId/_shell/route'
import { Route as PProjectIdShellIndexRouteImport } from './routes/p/$projectId/_shell/index'
import { Route as PProjectIdShellSettingsRouteRouteImport } from './routes/p/$projectId/_shell/settings/route'
import { Route as PProjectIdShellArtifactsIndexRouteImport } from './routes/p/$projectId/_shell/artifacts/index'
import { Route as PProjectIdShellArtifactsArtifactIdRouteImport } from './routes/p/$projectId/_shell/artifacts/$artifactId'
import { Route as PProjectIdShellReleasesIndexRouteImport } from './routes/p/$projectId/_shell/releases/index'
import { Route as PProjectIdShellReleasesVersionRouteImport } from './routes/p/$projectId/_shell/releases/$version'
import { Route as PProjectIdShellRunsIndexRouteImport } from './routes/p/$projectId/_shell/runs/index'
import { Route as PProjectIdShellRunsRunIdRouteImport } from './routes/p/$projectId/_shell/runs/$runId'
import { Route as PProjectIdShellSettingsIndexRouteImport } from './routes/p/$projectId/_shell/settings/index'
import { Route as PProjectIdShellSettingsBuildRouteImport } from './routes/p/$projectId/_shell/settings/build'
import { Route as PProjectIdShellSettingsConfigurationRouteImport } from './routes/p/$projectId/_shell/settings/configuration'
import { Route as PProjectIdShellSettingsCredentialsRouteImport } from './routes/p/$projectId/_shell/settings/credentials'
import { Route as PProjectIdShellSettingsEnvironmentsRouteImport } from './routes/p/$projectId/_shell/settings/environments'
import { Route as PProjectIdShellStoresIndexRouteImport } from './routes/p/$projectId/_shell/stores/index'
import { Route as PProjectIdShellStoresStoreIdRouteImport } from './routes/p/$projectId/_shell/stores/$storeId'
import { Route as PProjectIdShellTestsIndexRouteImport } from './routes/p/$projectId/_shell/tests/index'
import { Route as PProjectIdShellWorkflowsIndexRouteImport } from './routes/p/$projectId/_shell/workflows/index'
import { Route as PProjectIdShellWorkflowsWorkflowIdRouteImport } from './routes/p/$projectId/_shell/workflows/$workflowId'
import { Route as PProjectIdShellSettingsPublishersIndexRouteImport } from './routes/p/$projectId/_shell/settings/publishers/index'
import { Route as PProjectIdShellSettingsPublishersPublisherIdRouteImport } from './routes/p/$projectId/_shell/settings/publishers/$publisherId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PProjectIdRouteRoute = PProjectIdRouteRouteImport.update({
  id: '/p/$projectId',
  path: '/p/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const PProjectIdShellRouteRoute = PProjectIdShellRouteRouteImport.update({
  id: '/_shell',
  getParentRoute: () => PProjectIdRouteRoute,
} as any)
const PProjectIdShellIndexRoute = PProjectIdShellIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PProjectIdShellRouteRoute,
} as any)
const PProjectIdShellSettingsRouteRoute =
  PProjectIdShellSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => PProjectIdShellRouteRoute,
  } as any)
const PProjectIdShellArtifactsIndexRoute =
  PProjectIdShellArtifactsIndexRouteImport.update({
    id: '/artifacts/',
    path: '/artifacts/',
    getParentRoute: () => PProjectIdShellRouteRoute,
  } as any)
const PProjectIdShellArtifactsArtifactIdRoute =
  PProjectIdShellArtifactsArtifactIdRouteImport.update({
    id: '/artifacts/$artifactId',
    path: '/artifacts/$artifactId',
    getParentRoute: () => PProjectIdShellRouteRoute,
  } as any)
const PProjectIdShellReleasesIndexRoute =
  PProjectIdShellReleasesIndexRouteImport.update({
    id: '/releases/',
    path: '/releases/',
    getParentRoute: () => PProjectIdShellRouteRoute,
  } as any)
const PProjectIdShellReleasesVersionRoute =
  PProjectIdShellReleasesVersionRouteImport.update({
    id: '/releases/$version',
    path: '/releases/$version',
    getParentRoute: () => PProjectIdShellRouteRoute,
  } as any)
const PProjectIdShellRunsIndexRoute =
  PProjectIdShellRunsIndexRouteImport.update({
    id: '/runs/',
    path: '/runs/',
    getParentRoute: () => PProjectIdShellRouteRoute,
  } as any)
const PProjectIdShellRunsRunIdRoute =
  PProjectIdShellRunsRunIdRouteImport.update({
    id: '/runs/$runId',
    path: '/runs/$runId',
    getParentRoute: () => PProjectIdShellRouteRoute,
  } as any)
const PProjectIdShellSettingsIndexRoute =
  PProjectIdShellSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => PProjectIdShellSettingsRouteRoute,
  } as any)
const PProjectIdShellSettingsBuildRoute =
  PProjectIdShellSettingsBuildRouteImport.update({
    id: '/build',
    path: '/build',
    getParentRoute: () => PProjectIdShellSettingsRouteRoute,
  } as any)
const PProjectIdShellSettingsConfigurationRoute =
  PProjectIdShellSettingsConfigurationRouteImport.update({
    id: '/configuration',
    path: '/configuration',
    getParentRoute: () => PProjectIdShellSettingsRouteRoute,
  } as any)
const PProjectIdShellSettingsCredentialsRoute =
  PProjectIdShellSettingsCredentialsRouteImport.update({
    id: '/credentials',
    path: '/credentials',
    getParentRoute: () => PProjectIdShellSettingsRouteRoute,
  } as any)
const PProjectIdShellSettingsEnvironmentsRoute =
  PProjectIdShellSettingsEnvironmentsRouteImport.update({
    id: '/environments',
    path: '/environments',
    getParentRoute: () => PProjectIdShellSettingsRouteRoute,
  } as any)
const PProjectIdShellStoresIndexRoute =
  PProjectIdShellStoresIndexRouteImport.update({
    id: '/stores/',
    path: '/stores/',
    getParentRoute: () => PProjectIdShellRouteRoute,
  } as any)
const PProjectIdShellStoresStoreIdRoute =
  PProjectIdShellStoresStoreIdRouteImport.update({
    id: '/stores/$storeId',
    path: '/stores/$storeId',
    getParentRoute: () => PProjectIdShellRouteRoute,
  } as any)
const PProjectIdShellTestsIndexRoute =
  PProjectIdShellTestsIndexRouteImport.update({
    id: '/tests/',
    path: '/tests/',
    getParentRoute: () => PProjectIdShellRouteRoute,
  } as any)
const PProjectIdShellWorkflowsIndexRoute =
  PProjectIdShellWorkflowsIndexRouteImport.update({
    id: '/workflows/',
    path: '/workflows/',
    getParentRoute: () => PProjectIdShellRouteRoute,
  } as any)
const PProjectIdShellWorkflowsWorkflowIdRoute =
  PProjectIdShellWorkflowsWorkflowIdRouteImport.update({
    id: '/workflows/$workflowId',
    path: '/workflows/$workflowId',
    getParentRoute: () => PProjectIdShellRouteRoute,
  } as any)
const PProjectIdShellSettingsPublishersIndexRoute =
  PProjectIdShellSettingsPublishersIndexRouteImport.update({
    id: '/publishers/',
    path: '/publishers/',
    getParentRoute: () => PProjectIdShellSettingsRouteRoute,
  } as any)
const PProjectIdShellSettingsPublishersPublisherIdRoute =
  PProjectIdShellSettingsPublishersPublisherIdRouteImport.update({
    id: '/publishers/$publisherId',
    path: '/publishers/$publisherId',
    getParentRoute: () => PProjectIdShellSettingsRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/p/$projectId': typeof PProjectIdRouteRouteWithChildren
  '/p/$projectId/settings': typeof PProjectIdShellSettingsRouteRouteWithChildren
  '/p/$projectId/': typeof PProjectIdShellIndexRoute
  '/p/$projectId/artifacts/$artifactId': typeof PProjectIdShellArtifactsArtifactIdRoute
  '/p/$projectId/releases/$version': typeof PProjectIdShellReleasesVersionRoute
  '/p/$projectId/runs/$runId': typeof PProjectIdShellRunsRunIdRoute
  '/p/$projectId/settings/build': typeof PProjectIdShellSettingsBuildRoute
  '/p/$projectId/settings/configuration': typeof PProjectIdShellSettingsConfigurationRoute
  '/p/$projectId/settings/credentials': typeof PProjectIdShellSettingsCredentialsRoute
  '/p/$projectId/settings/environments': typeof PProjectIdShellSettingsEnvironmentsRoute
  '/p/$projectId/stores/$storeId': typeof PProjectIdShellStoresStoreIdRoute
  '/p/$projectId/workflows/$workflowId': typeof PProjectIdShellWorkflowsWorkflowIdRoute
  '/p/$projectId/artifacts/': typeof PProjectIdShellArtifactsIndexRoute
  '/p/$projectId/releases/': typeof PProjectIdShellReleasesIndexRoute
  '/p/$projectId/runs/': typeof PProjectIdShellRunsIndexRoute
  '/p/$projectId/settings/': typeof PProjectIdShellSettingsIndexRoute
  '/p/$projectId/stores/': typeof PProjectIdShellStoresIndexRoute
  '/p/$projectId/tests/': typeof PProjectIdShellTestsIndexRoute
  '/p/$projectId/workflows/': typeof PProjectIdShellWorkflowsIndexRoute
  '/p/$projectId/settings/publishers/$publisherId': typeof PProjectIdShellSettingsPublishersPublisherIdRoute
  '/p/$projectId/settings/publishers/': typeof PProjectIdShellSettingsPublishersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/p/$projectId': typeof PProjectIdShellIndexRoute
  '/p/$projectId/artifacts/$artifactId': typeof PProjectIdShellArtifactsArtifactIdRoute
  '/p/$projectId/releases/$version': typeof PProjectIdShellReleasesVersionRoute
  '/p/$projectId/runs/$runId': typeof PProjectIdShellRunsRunIdRoute
  '/p/$projectId/settings/build': typeof PProjectIdShellSettingsBuildRoute
  '/p/$projectId/settings/configuration': typeof PProjectIdShellSettingsConfigurationRoute
  '/p/$projectId/settings/credentials': typeof PProjectIdShellSettingsCredentialsRoute
  '/p/$projectId/settings/environments': typeof PProjectIdShellSettingsEnvironmentsRoute
  '/p/$projectId/stores/$storeId': typeof PProjectIdShellStoresStoreIdRoute
  '/p/$projectId/workflows/$workflowId': typeof PProjectIdShellWorkflowsWorkflowIdRoute
  '/p/$projectId/artifacts': typeof PProjectIdShellArtifactsIndexRoute
  '/p/$projectId/releases': typeof PProjectIdShellReleasesIndexRoute
  '/p/$projectId/runs': typeof PProjectIdShellRunsIndexRoute
  '/p/$projectId/settings': typeof PProjectIdShellSettingsIndexRoute
  '/p/$projectId/stores': typeof PProjectIdShellStoresIndexRoute
  '/p/$projectId/tests': typeof PProjectIdShellTestsIndexRoute
  '/p/$projectId/workflows': typeof PProjectIdShellWorkflowsIndexRoute
  '/p/$projectId/settings/publishers/$publisherId': typeof PProjectIdShellSettingsPublishersPublisherIdRoute
  '/p/$projectId/settings/publishers': typeof PProjectIdShellSettingsPublishersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/p/$projectId': typeof PProjectIdRouteRouteWithChildren
  '/p/$projectId/_shell': typeof PProjectIdShellRouteRouteWithChildren
  '/p/$projectId/_shell/settings': typeof PProjectIdShellSettingsRouteRouteWithChildren
  '/p/$projectId/_shell/': typeof PProjectIdShellIndexRoute
  '/p/$projectId/_shell/artifacts/$artifactId': typeof PProjectIdShellArtifactsArtifactIdRoute
  '/p/$projectId/_shell/releases/$version': typeof PProjectIdShellReleasesVersionRoute
  '/p/$projectId/_shell/runs/$runId': typeof PProjectIdShellRunsRunIdRoute
  '/p/$projectId/_shell/settings/build': typeof PProjectIdShellSettingsBuildRoute
  '/p/$projectId/_shell/settings/configuration': typeof PProjectIdShellSettingsConfigurationRoute
  '/p/$projectId/_shell/settings/credentials': typeof PProjectIdShellSettingsCredentialsRoute
  '/p/$projectId/_shell/settings/environments': typeof PProjectIdShellSettingsEnvironmentsRoute
  '/p/$projectId/_shell/stores/$storeId': typeof PProjectIdShellStoresStoreIdRoute
  '/p/$projectId/_shell/workflows/$workflowId': typeof PProjectIdShellWorkflowsWorkflowIdRoute
  '/p/$projectId/_shell/artifacts/': typeof PProjectIdShellArtifactsIndexRoute
  '/p/$projectId/_shell/releases/': typeof PProjectIdShellReleasesIndexRoute
  '/p/$projectId/_shell/runs/': typeof PProjectIdShellRunsIndexRoute
  '/p/$projectId/_shell/settings/': typeof PProjectIdShellSettingsIndexRoute
  '/p/$projectId/_shell/stores/': typeof PProjectIdShellStoresIndexRoute
  '/p/$projectId/_shell/tests/': typeof PProjectIdShellTestsIndexRoute
  '/p/$projectId/_shell/workflows/': typeof PProjectIdShellWorkflowsIndexRoute
  '/p/$projectId/_shell/settings/publishers/$publisherId': typeof PProjectIdShellSettingsPublishersPublisherIdRoute
  '/p/$projectId/_shell/settings/publishers/': typeof PProjectIdShellSettingsPublishersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/p/$projectId'
    | '/p/$projectId/settings'
    | '/p/$projectId/'
    | '/p/$projectId/artifacts/$artifactId'
    | '/p/$projectId/releases/$version'
    | '/p/$projectId/runs/$runId'
    | '/p/$projectId/settings/build'
    | '/p/$projectId/settings/configuration'
    | '/p/$projectId/settings/credentials'
    | '/p/$projectId/settings/environments'
    | '/p/$projectId/stores/$storeId'
    | '/p/$projectId/workflows/$workflowId'
    | '/p/$projectId/artifacts/'
    | '/p/$projectId/releases/'
    | '/p/$projectId/runs/'
    | '/p/$projectId/settings/'
    | '/p/$projectId/stores/'
    | '/p/$projectId/tests/'
    | '/p/$projectId/workflows/'
    | '/p/$projectId/settings/publishers/$publisherId'
    | '/p/$projectId/settings/publishers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/p/$projectId'
    | '/p/$projectId/artifacts/$artifactId'
    | '/p/$projectId/releases/$version'
    | '/p/$projectId/runs/$runId'
    | '/p/$projectId/settings/build'
    | '/p/$projectId/settings/configuration'
    | '/p/$projectId/settings/credentials'
    | '/p/$projectId/settings/environments'
    | '/p/$projectId/stores/$storeId'
    | '/p/$projectId/workflows/$workflowId'
    | '/p/$projectId/artifacts'
    | '/p/$projectId/releases'
    | '/p/$projectId/runs'
    | '/p/$projectId/settings'
    | '/p/$projectId/stores'
    | '/p/$projectId/tests'
    | '/p/$projectId/workflows'
    | '/p/$projectId/settings/publishers/$publisherId'
    | '/p/$projectId/settings/publishers'
  id:
    | '__root__'
    | '/'
    | '/p/$projectId'
    | '/p/$projectId/_shell'
    | '/p/$projectId/_shell/settings'
    | '/p/$projectId/_shell/'
    | '/p/$projectId/_shell/artifacts/$artifactId'
    | '/p/$projectId/_shell/releases/$version'
    | '/p/$projectId/_shell/runs/$runId'
    | '/p/$projectId/_shell/settings/build'
    | '/p/$projectId/_shell/settings/configuration'
    | '/p/$projectId/_shell/settings/credentials'
    | '/p/$projectId/_shell/settings/environments'
    | '/p/$projectId/_shell/stores/$storeId'
    | '/p/$projectId/_shell/workflows/$workflowId'
    | '/p/$projectId/_shell/artifacts/'
    | '/p/$projectId/_shell/releases/'
    | '/p/$projectId/_shell/runs/'
    | '/p/$projectId/_shell/settings/'
    | '/p/$projectId/_shell/stores/'
    | '/p/$projectId/_shell/tests/'
    | '/p/$projectId/_shell/workflows/'
    | '/p/$projectId/_shell/settings/publishers/$publisherId'
    | '/p/$projectId/_shell/settings/publishers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PProjectIdRouteRoute: typeof PProjectIdRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$projectId': {
      id: '/p/$projectId'
      path: '/p/$projectId'
      fullPath: '/p/$projectId'
      preLoaderRoute: typeof PProjectIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$projectId/_shell': {
      id: '/p/$projectId/_shell'
      path: ''
      fullPath: '/p/$projectId'
      preLoaderRoute: typeof PProjectIdShellRouteRouteImport
      parentRoute: typeof PProjectIdRouteRoute
    }
    '/p/$projectId/_shell/': {
      id: '/p/$projectId/_shell/'
      path: '/'
      fullPath: '/p/$projectId/'
      preLoaderRoute: typeof PProjectIdShellIndexRouteImport
      parentRoute: typeof PProjectIdShellRouteRoute
    }
    '/p/$projectId/_shell/settings': {
      id: '/p/$projectId/_shell/settings'
      path: '/settings'
      fullPath: '/p/$projectId/settings'
      preLoaderRoute: typeof PProjectIdShellSettingsRouteRouteImport
      parentRoute: typeof PProjectIdShellRouteRoute
    }
    '/p/$projectId/_shell/artifacts/': {
      id: '/p/$projectId/_shell/artifacts/'
      path: '/artifacts'
      fullPath: '/p/$projectId/artifacts/'
      preLoaderRoute: typeof PProjectIdShellArtifactsIndexRouteImport
      parentRoute: typeof PProjectIdShellRouteRoute
    }
    '/p/$projectId/_shell/artifacts/$artifactId': {
      id: '/p/$projectId/_shell/artifacts/$artifactId'
      path: '/artifacts/$artifactId'
      fullPath: '/p/$projectId/artifacts/$artifactId'
      preLoaderRoute: typeof PProjectIdShellArtifactsArtifactIdRouteImport
      parentRoute: typeof PProjectIdShellRouteRoute
    }
    '/p/$projectId/_shell/releases/': {
      id: '/p/$projectId/_shell/releases/'
      path: '/releases'
      fullPath: '/p/$projectId/releases/'
      preLoaderRoute: typeof PProjectIdShellReleasesIndexRouteImport
      parentRoute: typeof PProjectIdShellRouteRoute
    }
    '/p/$projectId/_shell/releases/$version': {
      id: '/p/$projectId/_shell/releases/$version'
      path: '/releases/$version'
      fullPath: '/p/$projectId/releases/$version'
      preLoaderRoute: typeof PProjectIdShellReleasesVersionRouteImport
      parentRoute: typeof PProjectIdShellRouteRoute
    }
    '/p/$projectId/_shell/runs/': {
      id: '/p/$projectId/_shell/runs/'
      path: '/runs'
      fullPath: '/p/$projectId/runs/'
      preLoaderRoute: typeof PProjectIdShellRunsIndexRouteImport
      parentRoute: typeof PProjectIdShellRouteRoute
    }
    '/p/$projectId/_shell/runs/$runId': {
      id: '/p/$projectId/_shell/runs/$runId'
      path: '/runs/$runId'
      fullPath: '/p/$projectId/runs/$runId'
      preLoaderRoute: typeof PProjectIdShellRunsRunIdRouteImport
      parentRoute: typeof PProjectIdShellRouteRoute
    }
    '/p/$projectId/_shell/settings/': {
      id: '/p/$projectId/_shell/settings/'
      path: '/'
      fullPath: '/p/$projectId/settings/'
      preLoaderRoute: typeof PProjectIdShellSettingsIndexRouteImport
      parentRoute: typeof PProjectIdShellSettingsRouteRoute
    }
    '/p/$projectId/_shell/settings/build': {
      id: '/p/$projectId/_shell/settings/build'
      path: '/build'
      fullPath: '/p/$projectId/settings/build'
      preLoaderRoute: typeof PProjectIdShellSettingsBuildRouteImport
      parentRoute: typeof PProjectIdShellSettingsRouteRoute
    }
    '/p/$projectId/_shell/settings/configuration': {
      id: '/p/$projectId/_shell/settings/configuration'
      path: '/configuration'
      fullPath: '/p/$projectId/settings/configuration'
      preLoaderRoute: typeof PProjectIdShellSettingsConfigurationRouteImport
      parentRoute: typeof PProjectIdShellSettingsRouteRoute
    }
    '/p/$projectId/_shell/settings/credentials': {
      id: '/p/$projectId/_shell/settings/credentials'
      path: '/credentials'
      fullPath: '/p/$projectId/settings/credentials'
      preLoaderRoute: typeof PProjectIdShellSettingsCredentialsRouteImport
      parentRoute: typeof PProjectIdShellSettingsRouteRoute
    }
    '/p/$projectId/_shell/settings/environments': {
      id: '/p/$projectId/_shell/settings/environments'
      path: '/environments'
      fullPath: '/p/$projectId/settings/environments'
      preLoaderRoute: typeof PProjectIdShellSettingsEnvironmentsRouteImport
      parentRoute: typeof PProjectIdShellSettingsRouteRoute
    }
    '/p/$projectId/_shell/stores/': {
      id: '/p/$projectId/_shell/stores/'
      path: '/stores'
      fullPath: '/p/$projectId/stores/'
      preLoaderRoute: typeof PProjectIdShellStoresIndexRouteImport
      parentRoute: typeof PProjectIdShellRouteRoute
    }
    '/p/$projectId/_shell/stores/$storeId': {
      id: '/p/$projectId/_shell/stores/$storeId'
      path: '/stores/$storeId'
      fullPath: '/p/$projectId/stores/$storeId'
      preLoaderRoute: typeof PProjectIdShellStoresStoreIdRouteImport
      parentRoute: typeof PProjectIdShellRouteRoute
    }
    '/p/$projectId/_shell/tests/': {
      id: '/p/$projectId/_shell/tests/'
      path: '/tests'
      fullPath: '/p/$projectId/tests/'
      preLoaderRoute: typeof PProjectIdShellTestsIndexRouteImport
      parentRoute: typeof PProjectIdShellRouteRoute
    }
    '/p/$projectId/_shell/workflows/': {
      id: '/p/$projectId/_shell/workflows/'
      path: '/workflows'
      fullPath: '/p/$projectId/workflows/'
      preLoaderRoute: typeof PProjectIdShellWorkflowsIndexRouteImport
      parentRoute: typeof PProjectIdShellRouteRoute
    }
    '/p/$projectId/_shell/workflows/$workflowId': {
      id: '/p/$projectId/_shell/workflows/$workflowId'
      path: '/workflows/$workflowId'
      fullPath: '/p/$projectId/workflows/$workflowId'
      preLoaderRoute: typeof PProjectIdShellWorkflowsWorkflowIdRouteImport
      parentRoute: typeof PProjectIdShellRouteRoute
    }
    '/p/$projectId/_shell/settings/publishers/': {
      id: '/p/$projectId/_shell/settings/publishers/'
      path: '/publishers'
      fullPath: '/p/$projectId/settings/publishers/'
      preLoaderRoute: typeof PProjectIdShellSettingsPublishersIndexRouteImport
      parentRoute: typeof PProjectIdShellSettingsRouteRoute
    }
    '/p/$projectId/_shell/settings/publishers/$publisherId': {
      id: '/p/$projectId/_shell/settings/publishers/$publisherId'
      path: '/publishers/$publisherId'
      fullPath: '/p/$projectId/settings/publishers/$publisherId'
      preLoaderRoute: typeof PProjectIdShellSettingsPublishersPublisherIdRouteImport
      parentRoute: typeof PProjectIdShellSettingsRouteRoute
    }
  }
}

interface PProjectIdShellSettingsRouteRouteChildren {
  PProjectIdShellSettingsBuildRoute: typeof PProjectIdShellSettingsBuildRoute
  PProjectIdShellSettingsConfigurationRoute: typeof PProjectIdShellSettingsConfigurationRoute
  PProjectIdShellSettingsCredentialsRoute: typeof PProjectIdShellSettingsCredentialsRoute
  PProjectIdShellSettingsEnvironmentsRoute: typeof PProjectIdShellSettingsEnvironmentsRoute
  PProjectIdShellSettingsIndexRoute: typeof PProjectIdShellSettingsIndexRoute
  PProjectIdShellSettingsPublishersPublisherIdRoute: typeof PProjectIdShellSettingsPublishersPublisherIdRoute
  PProjectIdShellSettingsPublishersIndexRoute: typeof PProjectIdShellSettingsPublishersIndexRoute
}

const PProjectIdShellSettingsRouteRouteChildren: PProjectIdShellSettingsRouteRouteChildren =
  {
    PProjectIdShellSettingsBuildRoute: PProjectIdShellSettingsBuildRoute,
    PProjectIdShellSettingsConfigurationRoute:
      PProjectIdShellSettingsConfigurationRoute,
    PProjectIdShellSettingsCredentialsRoute:
      PProjectIdShellSettingsCredentialsRoute,
    PProjectIdShellSettingsEnvironmentsRoute:
      PProjectIdShellSettingsEnvironmentsRoute,
    PProjectIdShellSettingsIndexRoute: PProjectIdShellSettingsIndexRoute,
    PProjectIdShellSettingsPublishersPublisherIdRoute:
      PProjectIdShellSettingsPublishersPublisherIdRoute,
    PProjectIdShellSettingsPublishersIndexRoute:
      PProjectIdShellSettingsPublishersIndexRoute,
  }

const PProjectIdShellSettingsRouteRouteWithChildren =
  PProjectIdShellSettingsRouteRoute._addFileChildren(
    PProjectIdShellSettingsRouteRouteChildren,
  )

interface PProjectIdShellRouteRouteChildren {
  PProjectIdShellSettingsRouteRoute: typeof PProjectIdShellSettingsRouteRouteWithChildren
  PProjectIdShellIndexRoute: typeof PProjectIdShellIndexRoute
  PProjectIdShellArtifactsArtifactIdRoute: typeof PProjectIdShellArtifactsArtifactIdRoute
  PProjectIdShellReleasesVersionRoute: typeof PProjectIdShellReleasesVersionRoute
  PProjectIdShellRunsRunIdRoute: typeof PProjectIdShellRunsRunIdRoute
  PProjectIdShellStoresStoreIdRoute: typeof PProjectIdShellStoresStoreIdRoute
  PProjectIdShellWorkflowsWorkflowIdRoute: typeof PProjectIdShellWorkflowsWorkflowIdRoute
  PProjectIdShellArtifactsIndexRoute: typeof PProjectIdShellArtifactsIndexRoute
  PProjectIdShellReleasesIndexRoute: typeof PProjectIdShellReleasesIndexRoute
  PProjectIdShellRunsIndexRoute: typeof PProjectIdShellRunsIndexRoute
  PProjectIdShellStoresIndexRoute: typeof PProjectIdShellStoresIndexRoute
  PProjectIdShellTestsIndexRoute: typeof PProjectIdShellTestsIndexRoute
  PProjectIdShellWorkflowsIndexRoute: typeof PProjectIdShellWorkflowsIndexRoute
}

const PProjectIdShellRouteRouteChildren: PProjectIdShellRouteRouteChildren = {
  PProjectIdShellSettingsRouteRoute:
    PProjectIdShellSettingsRouteRouteWithChildren,
  PProjectIdShellIndexRoute: PProjectIdShellIndexRoute,
  PProjectIdShellArtifactsArtifactIdRoute:
    PProjectIdShellArtifactsArtifactIdRoute,
  PProjectIdShellReleasesVersionRoute: PProjectIdShellReleasesVersionRoute,
  PProjectIdShellRunsRunIdRoute: PProjectIdShellRunsRunIdRoute,
  PProjectIdShellStoresStoreIdRoute: PProjectIdShellStoresStoreIdRoute,
  PProjectIdShellWorkflowsWorkflowIdRoute:
    PProjectIdShellWorkflowsWorkflowIdRoute,
  PProjectIdShellArtifactsIndexRoute: PProjectIdShellArtifactsIndexRoute,
  PProjectIdShellReleasesIndexRoute: PProjectIdShellReleasesIndexRoute,
  PProjectIdShellRunsIndexRoute: PProjectIdShellRunsIndexRoute,
  PProjectIdShellStoresIndexRoute: PProjectIdShellStoresIndexRoute,
  PProjectIdShellTestsIndexRoute: PProjectIdShellTestsIndexRoute,
  PProjectIdShellWorkflowsIndexRoute: PProjectIdShellWorkflowsIndexRoute,
}

const PProjectIdShellRouteRouteWithChildren =
  PProjectIdShellRouteRoute._addFileChildren(PProjectIdShellRouteRouteChildren)

interface PProjectIdRouteRouteChildren {
  PProjectIdShellRouteRoute: typeof PProjectIdShellRouteRouteWithChildren
}

const PProjectIdRouteRouteChildren: PProjectIdRouteRouteChildren = {
  PProjectIdShellRouteRoute: PProjectIdShellRouteRouteWithChildren,
}

const PProjectIdRouteRouteWithChildren = PProjectIdRouteRoute._addFileChildren(
  PProjectIdRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PProjectIdRouteRoute: PProjectIdRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
