/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/capabilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** What this deployment can do */
        get: operations["getCapabilities"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List projects */
        get: operations["listProjects"];
        put?: never;
        /** Register (local) or create (hosted) a project */
        post: operations["createProject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects/{projectId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        /** Read one project */
        get: operations["getProject"];
        put?: never;
        post?: never;
        /**
         * Remove a project
         * @description In local mode this only unregisters the directory. Nothing on disk is
         *     deleted — the checkout is the user's, not Studio's.
         */
        delete: operations["deleteProject"];
        options?: never;
        head?: never;
        /** Rename a project */
        patch: operations["updateProject"];
        trace?: never;
    };
    "/v1/projects/{projectId}/stores": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        /**
         * List store connections
         * @description Returns every supported store, configured or not, so the page can offer
         *     what the project could connect to as well as what it already has.
         */
        get: operations["listStores"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects/{projectId}/stores/{store}/apps": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
                store: components["parameters"]["Store"];
            };
            cookie?: never;
        };
        /** List the apps registered under one store */
        get: operations["listStoreApps"];
        put?: never;
        /**
         * Register an app under a store
         * @description Appends an entry to the store's `apps:` list in `.fastforge/config.yaml`.
         */
        post: operations["createStoreApp"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects/{projectId}/store-apps": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        /**
         * List every app across all stores
         * @description In configuration order. The project shell reads this once to build its
         *     sidebar, which is why it exists alongside the per-store list.
         */
        get: operations["listAllStoreApps"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects/{projectId}/store-apps/{storeAppId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
                /**
                 * @description `<store>:<identifier>`, URL-encoded — e.g. `appstore%3Acom.example.myapp`.
                 * @example appstore:com.example.myapp
                 */
                storeAppId: components["parameters"]["StoreAppId"];
            };
            cookie?: never;
        };
        /** Read one store app */
        get: operations["getStoreApp"];
        put?: never;
        post?: never;
        /**
         * Unregister a store app
         * @description Removes the config entry. The pulled catalog on disk is left alone.
         */
        delete: operations["deleteStoreApp"];
        options?: never;
        head?: never;
        /**
         * Edit a store app's metadata
         * @description The identifier is not editable: it is the app's identity on the store
         *     and the name of the directory its catalog lives in.
         */
        patch: operations["updateStoreApp"];
        trace?: never;
    };
    "/v1/projects/{projectId}/store-apps/{storeAppId}/listing": {
        parameters: {
            query?: {
                /**
                 * @description Defaults to `en-US` when the catalog has it, otherwise the first locale — so the page does not change every time the filesystem reorders.
                 * @example en-US
                 */
                locale?: string;
                /** @description An App Store version (`IOS/1.2.0`) or a Google Play track. Defaults to the newest version, or the production track. */
                version?: string;
            };
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
                /**
                 * @description `<store>:<identifier>`, URL-encoded — e.g. `appstore%3Acom.example.myapp`.
                 * @example appstore:com.example.myapp
                 */
                storeAppId: components["parameters"]["StoreAppId"];
            };
            cookie?: never;
        };
        /**
         * The listing a store would show
         * @description Assembled from the pulled catalog: the product page's shape rather than
         *     the files'. Text is merged across versions nearest-first, because `pull`
         *     writes only the fields a version changed — reading one version's file
         *     alone would blank out an listing that is perfectly complete.
         *
         *     An app whose catalog has never been pulled is not an error: the listing
         *     comes back with `empty: true`.
         */
        get: operations["getStoreListing"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects/{projectId}/store-apps/{storeAppId}/catalog": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
                /**
                 * @description `<store>:<identifier>`, URL-encoded — e.g. `appstore%3Acom.example.myapp`.
                 * @example appstore:com.example.myapp
                 */
                storeAppId: components["parameters"]["StoreAppId"];
            };
            cookie?: never;
        };
        /**
         * Read the local catalog tree
         * @description The whole tree in one response, children inline. A catalog is a few
         *     hundred files at most, and the UI wants its shape up front rather than
         *     a request per expanded folder.
         */
        get: operations["getCatalogTree"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects/{projectId}/store-apps/{storeAppId}/catalog/file": {
        parameters: {
            query: {
                /**
                 * @description Path relative to the catalog directory. Must not escape it.
                 * @example versions/IOS/1.0.0/en-US/localization.yaml
                 */
                path: components["parameters"]["CatalogPath"];
            };
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
                /**
                 * @description `<store>:<identifier>`, URL-encoded — e.g. `appstore%3Acom.example.myapp`.
                 * @example appstore:com.example.myapp
                 */
                storeAppId: components["parameters"]["StoreAppId"];
            };
            cookie?: never;
        };
        /** Read one text file from the catalog */
        get: operations["getCatalogFile"];
        /** Write one text file back to the catalog */
        put: operations["putCatalogFile"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects/{projectId}/store-apps/{storeAppId}/catalog/raw": {
        parameters: {
            query: {
                /**
                 * @description Path relative to the catalog directory. Must not escape it.
                 * @example versions/IOS/1.0.0/en-US/localization.yaml
                 */
                path: components["parameters"]["CatalogPath"];
            };
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
                /**
                 * @description `<store>:<identifier>`, URL-encoded — e.g. `appstore%3Acom.example.myapp`.
                 * @example appstore:com.example.myapp
                 */
                storeAppId: components["parameters"]["StoreAppId"];
            };
            cookie?: never;
        };
        /** Fetch a screenshot or preview as bytes */
        get: operations["getCatalogRaw"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects/{projectId}/store-apps/{storeAppId}/catalog/pull": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
                /**
                 * @description `<store>:<identifier>`, URL-encoded — e.g. `appstore%3Acom.example.myapp`.
                 * @example appstore:com.example.myapp
                 */
                storeAppId: components["parameters"]["StoreAppId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Pull catalog data from the store
         * @description Starts a run and returns immediately. Follow
         *     `GET /v1/runs/{runId}/events` for progress.
         */
        post: operations["pullCatalog"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects/{projectId}/store-apps/{storeAppId}/catalog/push": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
                /**
                 * @description `<store>:<identifier>`, URL-encoded — e.g. `appstore%3Acom.example.myapp`.
                 * @example appstore:com.example.myapp
                 */
                storeAppId: components["parameters"]["StoreAppId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Push the local catalog to the store */
        post: operations["pushCatalog"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/runs/{runId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        /** Read a run */
        get: operations["getRun"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/runs/{runId}/events": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        /**
         * Stream a run's progress
         * @description Server-sent events. Each frame's `id` is the event's `seq`, so a
         *     reconnecting client resumes with `Last-Event-ID` instead of replaying
         *     the whole run. The stream closes once the run reaches a terminal state;
         *     the final frame carries `status`.
         */
        get: operations["streamRunEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/runs/{runId}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel a run */
        post: operations["cancelRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/fs/browse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List directories, for the "add project" picker
         * @description Local mode only — a browser cannot hand back a real path. Restricted to
         *     the user's home directory, and never returns file contents. Answers
         *     `404 CAPABILITY_UNAVAILABLE` when `capabilities.localFs` is false.
         */
        get: operations["browseFilesystem"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorEnvelope: {
            error: {
                /**
                 * @description Stable and machine-readable; clients branch on this.
                 * @example PROJECT_NOT_FOUND
                 */
                code: string;
                /** @description For a human reading a toast or a log line. */
                message: string;
            };
        };
        /** @enum {string} */
        StudioMode: "local" | "cloud";
        Capabilities: {
            mode: components["schemas"]["StudioMode"];
            /** @description More than one workspace exists, so the header needs a switcher. */
            workspaces: boolean;
            /** @description Runs are queued before they execute, so a pending count is meaningful. */
            runQueue: boolean;
            members: boolean;
            accessTokens: boolean;
            webhooks: boolean;
            billing: boolean;
            /** @description The host can browse the local filesystem, so "add project" can offer a directory picker instead of asking for a pasted path. */
            localFs: boolean;
            /** @description Catalog pull and push can execute here. */
            catalogSync: boolean;
        };
        /** @enum {string} */
        Platform: "android" | "ios" | "macos" | "windows" | "linux" | "web";
        Project: {
            id: string;
            name: string;
            /** @description Local checkout. Local mode only. */
            path?: string;
            /** @description Git remote. Hosted mode only. */
            repo?: string;
            platforms: components["schemas"]["Platform"][];
            /** @description Whether `.fastforge/config.yaml` exists. Without it there are no stores to read, which is what the stores page's empty state says. */
            hasFastforgeConfig: boolean;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        ProjectSummary: {
            id: string;
            name: string;
            path?: string;
            platforms: components["schemas"]["Platform"][];
            hasFastforgeConfig: boolean;
            /** @description The registry points at a directory that no longer exists. */
            missing: boolean;
        };
        CreateProjectRequest: {
            /** @description Absolute path to an existing checkout. Local mode. */
            path?: string;
            /** @description Defaults to the directory name in local mode. */
            name?: string;
            repo?: string;
        };
        UpdateProjectRequest: {
            name?: string;
        };
        /** @enum {string} */
        StoreKind: "appstore" | "googleplay";
        /** @enum {string} */
        AuthType: "api_key" | "username_password" | "service_account" | "unknown";
        AuthFieldSource: {
            /**
             * @description Config field name, e.g. `key_id`.
             * @example key_id
             */
            field: string;
            /**
             * @description `config`, `env:NAME`, or `unset` — never a credential value.
             * @example env:APP_STORE_CONNECT_KEY_ID
             */
            source: string;
            /** @description Environment variables that would satisfy a missing field. */
            candidates?: string[];
        };
        /** @description Whether the credentials a store needs resolve. Studio never reads their values — only whether each field resolves, and from where. */
        AuthStatus: {
            /** @enum {string} */
            state: "ready";
            sources?: components["schemas"]["AuthFieldSource"][];
        } | {
            /** @enum {string} */
            state: "incomplete";
            missing: components["schemas"]["AuthFieldSource"][];
        } | {
            /** @enum {string} */
            state: "notConfigured";
        };
        StoreConnection: {
            store: components["schemas"]["StoreKind"];
            /** @example App Store Connect */
            name: string;
            description: string;
            /** @description Whether `.fastforge/config.yaml` has a section for this store. */
            configured: boolean;
            authType: components["schemas"]["AuthType"];
            authStatus: components["schemas"]["AuthStatus"];
            appCount: number;
        };
        StoreApp: {
            /**
             * @description `<store>:<identifier>`.
             * @example appstore:com.example.myapp
             */
            id: string;
            store: components["schemas"]["StoreKind"];
            /** @description `bundle_id` for App Store, `package_name` for Google Play. */
            identifier: string;
            name?: string;
            appId?: string;
            sku?: string;
            /** @description Google Play release track. */
            track?: string;
            platform: components["schemas"]["Platform"];
            catalog: components["schemas"]["CatalogState"];
        };
        CreateStoreAppRequest: {
            /** @example com.example.myapp */
            identifier: string;
            name?: string;
            appId?: string;
            sku?: string;
            track?: string;
        };
        UpdateStoreAppRequest: {
            name?: string;
            appId?: string;
            sku?: string;
            track?: string;
        };
        CatalogState: {
            /**
             * @description Project-relative directory.
             * @example .fastforge/stores/appstore/com.example.myapp
             */
            path: string;
            exists: boolean;
            /**
             * Format: date-time
             * @description Modification time of `.manifest.yaml` — when pull last ran.
             */
            lastPulledAt?: string;
            fileCount: number;
        };
        StoreListing: {
            storeAppId: string;
            store: components["schemas"]["StoreKind"];
            identifier: string;
            /** @description Every locale the catalog holds. */
            locales: string[];
            locale?: string;
            /** @description App Store versions (`IOS/1.2.0`), or Google Play tracks. */
            versions: string[];
            version?: string;
            name?: string;
            /** @description App Store subtitle, or Google Play's short description. */
            subtitle?: string;
            promotionalText?: string;
            description?: string;
            /** @description Release notes — from the version, or the track's release. */
            whatsNew?: string;
            keywords?: string;
            copyright?: string;
            marketingUrl?: string;
            supportUrl?: string;
            privacyPolicyUrl?: string;
            /** @description Category identifiers, primary first. */
            categories?: string[];
            media?: components["schemas"]["ListingMediaGroup"][];
            /** @description Google Play only. */
            tracks?: components["schemas"]["ListingTrack"][];
            /** @description The catalog has nothing for this locale and version. */
            empty: boolean;
        };
        ListingMediaGroup: {
            /**
             * @description The directory name the store uses.
             * @example APP_IPHONE_67
             */
            id: string;
            /** @example iPhone 6.7" */
            label: string;
            items: components["schemas"]["ListingMediaItem"][];
        };
        ListingMediaItem: {
            /** @description Relative to the catalog directory — fetch through `catalog/raw`. */
            path: string;
            name: string;
            kind: components["schemas"]["CatalogEntryKind"];
        };
        ListingTrack: {
            /** @example production */
            name: string;
            releases?: components["schemas"]["ListingTrackRelease"][];
        };
        ListingTrackRelease: {
            name?: string;
            /** @example completed */
            status?: string;
            versionCodes?: string[];
            userFraction?: number;
            releaseNotes?: string;
        };
        /** @enum {string} */
        CatalogEntryKind: "dir" | "yaml" | "image" | "video" | "other";
        CatalogEntry: {
            /** @description Path relative to the catalog directory. */
            path: string;
            name: string;
            kind: components["schemas"]["CatalogEntryKind"];
            size?: number;
            /** Format: date-time */
            modifiedAt?: string;
            children?: components["schemas"]["CatalogEntry"][];
        };
        CatalogTree: {
            root: string;
            exists: boolean;
            entries: components["schemas"]["CatalogEntry"][];
        };
        CatalogFile: {
            path: string;
            kind: components["schemas"]["CatalogEntryKind"];
            content: string;
            /** @description Content hash. Echo it back on write so a stale editor tab cannot clobber a catalog that `pull` has refreshed since. */
            etag: string;
        };
        PutCatalogFileRequest: {
            content: string;
            /** @description The `etag` from the read. Omit to write unconditionally. */
            etag?: string;
        };
        CatalogPushRequest: {
            /**
             * @description Report what would change without writing to the store.
             * @default false
             */
            dryRun: boolean;
        };
        /** @enum {string} */
        RunKind: "store.catalog.pull" | "store.catalog.push";
        /** @enum {string} */
        RunStatus: "queued" | "running" | "succeeded" | "failed" | "cancelled";
        Run: {
            id: string;
            kind: components["schemas"]["RunKind"];
            projectId: string;
            /** @description What the run acts on — a store app id for catalog runs. */
            targetId: string;
            status: components["schemas"]["RunStatus"];
            dryRun: boolean;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            startedAt?: string;
            /** Format: date-time */
            finishedAt?: string;
            error?: string;
        };
        /** @enum {string} */
        LogLevel: "debug" | "info" | "warn" | "error";
        Progress: {
            current: number;
            total?: number;
            label?: string;
        };
        RunEvent: {
            /** @description Monotonic per run; sent as the SSE event id. */
            seq: number;
            /** Format: date-time */
            at: string;
            level: components["schemas"]["LogLevel"];
            message: string;
            progress?: components["schemas"]["Progress"];
            /** @description Present on the final frame, so a stream-only client learns the outcome. */
            status?: components["schemas"]["RunStatus"];
        };
        DirectoryEntry: {
            name: string;
            path: string;
            /** @description The directory looks like a project Studio can register. */
            isProject: boolean;
        };
        DirectoryListing: {
            path: string;
            /** @description Absent at the root of the browsable area. */
            parent?: string;
            entries: components["schemas"]["DirectoryEntry"][];
        };
    };
    responses: {
        /** @description The request is malformed */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description No such resource, or the capability is not served here */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /**
         * @description Contracted, but not served by this build yet. Distinct from
         *     `404 CAPABILITY_UNAVAILABLE`, which means this deployment will never
         *     serve it: a client should report a 501 rather than hide the feature.
         */
        NotImplemented: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
    };
    parameters: {
        ProjectId: string;
        Store: components["schemas"]["StoreKind"];
        /**
         * @description `<store>:<identifier>`, URL-encoded — e.g. `appstore%3Acom.example.myapp`.
         * @example appstore:com.example.myapp
         */
        StoreAppId: string;
        /**
         * @description Path relative to the catalog directory. Must not escape it.
         * @example versions/IOS/1.0.0/en-US/localization.yaml
         */
        CatalogPath: string;
        RunId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getCapabilities: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Capabilities"];
                    };
                };
            };
        };
    };
    listProjects: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["ProjectSummary"][];
                    };
                };
            };
        };
    };
    createProject: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProjectRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Project"];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            /** @description The directory is already registered */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    getProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Project"];
                    };
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    deleteProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Removed */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
        };
    };
    updateProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProjectRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Project"];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    listStores: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["StoreConnection"][];
                    };
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    listStoreApps: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
                store: components["parameters"]["Store"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["StoreApp"][];
                    };
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    createStoreApp: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
                store: components["parameters"]["Store"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateStoreAppRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["StoreApp"];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            /** @description That identifier is already registered under this store */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            501: components["responses"]["NotImplemented"];
        };
    };
    listAllStoreApps: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["StoreApp"][];
                    };
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getStoreApp: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
                /**
                 * @description `<store>:<identifier>`, URL-encoded — e.g. `appstore%3Acom.example.myapp`.
                 * @example appstore:com.example.myapp
                 */
                storeAppId: components["parameters"]["StoreAppId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["StoreApp"];
                    };
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    deleteStoreApp: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
                /**
                 * @description `<store>:<identifier>`, URL-encoded — e.g. `appstore%3Acom.example.myapp`.
                 * @example appstore:com.example.myapp
                 */
                storeAppId: components["parameters"]["StoreAppId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Removed */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
            501: components["responses"]["NotImplemented"];
        };
    };
    updateStoreApp: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
                /**
                 * @description `<store>:<identifier>`, URL-encoded — e.g. `appstore%3Acom.example.myapp`.
                 * @example appstore:com.example.myapp
                 */
                storeAppId: components["parameters"]["StoreAppId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateStoreAppRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["StoreApp"];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            501: components["responses"]["NotImplemented"];
        };
    };
    getStoreListing: {
        parameters: {
            query?: {
                /**
                 * @description Defaults to `en-US` when the catalog has it, otherwise the first locale — so the page does not change every time the filesystem reorders.
                 * @example en-US
                 */
                locale?: string;
                /** @description An App Store version (`IOS/1.2.0`) or a Google Play track. Defaults to the newest version, or the production track. */
                version?: string;
            };
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
                /**
                 * @description `<store>:<identifier>`, URL-encoded — e.g. `appstore%3Acom.example.myapp`.
                 * @example appstore:com.example.myapp
                 */
                storeAppId: components["parameters"]["StoreAppId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["StoreListing"];
                    };
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getCatalogTree: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
                /**
                 * @description `<store>:<identifier>`, URL-encoded — e.g. `appstore%3Acom.example.myapp`.
                 * @example appstore:com.example.myapp
                 */
                storeAppId: components["parameters"]["StoreAppId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["CatalogTree"];
                    };
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getCatalogFile: {
        parameters: {
            query: {
                /**
                 * @description Path relative to the catalog directory. Must not escape it.
                 * @example versions/IOS/1.0.0/en-US/localization.yaml
                 */
                path: components["parameters"]["CatalogPath"];
            };
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
                /**
                 * @description `<store>:<identifier>`, URL-encoded — e.g. `appstore%3Acom.example.myapp`.
                 * @example appstore:com.example.myapp
                 */
                storeAppId: components["parameters"]["StoreAppId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["CatalogFile"];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    putCatalogFile: {
        parameters: {
            query: {
                /**
                 * @description Path relative to the catalog directory. Must not escape it.
                 * @example versions/IOS/1.0.0/en-US/localization.yaml
                 */
                path: components["parameters"]["CatalogPath"];
            };
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
                /**
                 * @description `<store>:<identifier>`, URL-encoded — e.g. `appstore%3Acom.example.myapp`.
                 * @example appstore:com.example.myapp
                 */
                storeAppId: components["parameters"]["StoreAppId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PutCatalogFileRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["CatalogFile"];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            /**
             * @description The `etag` is stale — the file changed since it was read, most
             *     likely because `pull` ran. Re-read before writing.
             */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    getCatalogRaw: {
        parameters: {
            query: {
                /**
                 * @description Path relative to the catalog directory. Must not escape it.
                 * @example versions/IOS/1.0.0/en-US/localization.yaml
                 */
                path: components["parameters"]["CatalogPath"];
            };
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
                /**
                 * @description `<store>:<identifier>`, URL-encoded — e.g. `appstore%3Acom.example.myapp`.
                 * @example appstore:com.example.myapp
                 */
                storeAppId: components["parameters"]["StoreAppId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": string;
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    pullCatalog: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
                /**
                 * @description `<store>:<identifier>`, URL-encoded — e.g. `appstore%3Acom.example.myapp`.
                 * @example appstore:com.example.myapp
                 */
                storeAppId: components["parameters"]["StoreAppId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Run"];
                    };
                };
            };
            404: components["responses"]["NotFound"];
            /**
             * @description The store's credentials are incomplete, or a run is already in
             *     flight for this app.
             */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            501: components["responses"]["NotImplemented"];
        };
    };
    pushCatalog: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
                /**
                 * @description `<store>:<identifier>`, URL-encoded — e.g. `appstore%3Acom.example.myapp`.
                 * @example appstore:com.example.myapp
                 */
                storeAppId: components["parameters"]["StoreAppId"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["CatalogPushRequest"];
            };
        };
        responses: {
            /** @description Accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Run"];
                    };
                };
            };
            404: components["responses"]["NotFound"];
            /** @description Credentials are incomplete, or a run is already in flight */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            501: components["responses"]["NotImplemented"];
        };
    };
    getRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Run"];
                    };
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    streamRunEvents: {
        parameters: {
            query?: never;
            header?: {
                "Last-Event-ID"?: string;
            };
            path: {
                runId: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description An event stream of RunEvent frames */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["RunEvent"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    cancelRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Run"];
                    };
                };
            };
            404: components["responses"]["NotFound"];
            /** @description The run has already finished */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    browseFilesystem: {
        parameters: {
            query?: {
                /** @description Absolute path. Defaults to the user's home directory. */
                path?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["DirectoryListing"];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
}
